import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/employee.dart';
import '../models/client.dart';
import '../providers/employee_provider.dart';
import '../providers/client_provider.dart';

class DemoDataService {
  static Future<void> loadDemoData(WidgetRef ref) async {
    // Nur laden wenn keine Mitarbeiter vorhanden
    final employees = ref.read(employeesProvider);
    if (employees.valueOrNull != null && employees.valueOrNull!.isNotEmpty) return;

    final now = DateTime.now();

    final demoEmployees = [
      Employee(
        id: 'demo-ma-1',
        employeeNumber: 'MA-001',
        firstName: 'Sarah',
        lastName: 'Müller',
        email: 'demo@beispiel.de',
        phone: '030 12345678',
        dateOfBirth: DateTime(1990, 5, 14),
        hireDate: DateTime(2023, 3, 1),
        status: EmployeeStatus.active,
        contractType: ContractType.fullTime,
        hoursPerWeek: 38.5,
        hourlyRate: 22.50,
        position: 'Fachkraft Eingliederungshilfe',
        department: 'Eingliederungshilfe',
        qualifications: ['B.A. Soziale Arbeit', 'Systemische Beratung'],
        address: Address(street: 'Musterstr. 1', city: 'Berlin', postalCode: '10115', country: 'DE'),
        createdAt: now,
        updatedAt: now,
      ),
      Employee(
        id: 'demo-ma-2',
        employeeNumber: 'MA-002',
        firstName: 'Linh',
        lastName: 'Nguyen',
        email: 'demo2@beispiel.de',
        phone: '030 87654321',
        dateOfBirth: DateTime(1988, 11, 3),
        hireDate: DateTime(2024, 1, 15),
        status: EmployeeStatus.active,
        contractType: ContractType.partTime,
        hoursPerWeek: 30.0,
        hourlyRate: 21.00,
        position: 'Fachkraft Eingliederungshilfe',
        department: 'Eingliederungshilfe',
        qualifications: ['Dipl. Sozialpädagogin', 'Traumapädagogik'],
        address: Address(street: 'Beispielweg 5', city: 'Berlin', postalCode: '10245', country: 'DE'),
        createdAt: now,
        updatedAt: now,
      ),
      Employee(
        id: 'demo-ma-3',
        employeeNumber: 'MA-003',
        firstName: 'Thomas',
        lastName: 'Becker',
        email: 'demo3@beispiel.de',
        phone: '030 11223344',
        dateOfBirth: DateTime(1985, 7, 22),
        hireDate: DateTime(2022, 9, 1),
        status: EmployeeStatus.active,
        contractType: ContractType.fullTime,
        hoursPerWeek: 40.0,
        hourlyRate: 24.00,
        position: 'Teamleitung Eingliederungshilfe',
        department: 'Eingliederungshilfe',
        qualifications: ['M.A. Rehabilitationswissenschaften', 'ICF-Assessor'],
        address: Address(street: 'Hauptstr. 42', city: 'Berlin', postalCode: '10827', country: 'DE'),
        createdAt: now,
        updatedAt: now,
      ),
    ];

    for (final emp in demoEmployees) {
      try {
        await ref.read(employeesProvider.notifier).addEmployee(emp);
      } catch (_) {}
    }

    // 6 fiktive Klienten
    final demoClients = [
      Client(
        id: 'demo-kl-1',
        firstName: 'Anna',
        lastName: 'Schmidt',
        dateOfBirth: DateTime(1988, 3, 15),
        status: ClientStatus.active,
        priority: ClientPriority.medium,
        services: [ServiceType.ambulant, ServiceType.begleitung],
        betreuungSeit: DateTime(2025, 6, 1),
        hilfeTyp: HilfeTyp.eingliederungshilfe,
        fachleistungsstunden: 8,
        fachleistungsIntervall: FachleistungsIntervall.woechentlich,
        verbrauchteStunden: 42.5,
        kostenuebernahme: 'Bezirksamt Mitte',
        kostenuebernahmeVon: DateTime(2025, 6, 1),
        kostenuebernahmeBis: DateTime(2026, 5, 31),
        notes: 'Depressive Episode, Unterstützung bei Alltagsstruktur und sozialer Teilhabe',
        assignedEmployees: ['demo-ma-1'],
        responsibleEmployeeId: 'demo-ma-1',
        customFields: {},
        createdAt: now,
        updatedAt: now,
      ),
      Client(
        id: 'demo-kl-2',
        firstName: 'Emre',
        lastName: 'Yilmaz',
        dateOfBirth: DateTime(1995, 11, 22),
        status: ClientStatus.active,
        priority: ClientPriority.high,
        services: [ServiceType.ambulant, ServiceType.begleitung],
        betreuungSeit: DateTime(2025, 9, 15),
        hilfeTyp: HilfeTyp.eingliederungshilfe,
        fachleistungsstunden: 6,
        fachleistungsIntervall: FachleistungsIntervall.woechentlich,
        verbrauchteStunden: 28.0,
        kostenuebernahme: 'Bezirksamt Neukölln',
        kostenuebernahmeVon: DateTime(2025, 9, 15),
        kostenuebernahmeBis: DateTime(2026, 9, 14),
        notes: 'Schizophrenie, Begleitung Arztbesuche und Medikamentenmanagement',
        assignedEmployees: ['demo-ma-2'],
        responsibleEmployeeId: 'demo-ma-2',
        customFields: {},
        createdAt: now,
        updatedAt: now,
      ),
      Client(
        id: 'demo-kl-3',
        firstName: 'Christine',
        lastName: 'Weber',
        dateOfBirth: DateTime(1965, 7, 3),
        status: ClientStatus.active,
        priority: ClientPriority.medium,
        services: [ServiceType.ambulant],
        betreuungSeit: DateTime(2024, 11, 1),
        hilfeTyp: HilfeTyp.eingliederungshilfe,
        fachleistungsstunden: 5,
        fachleistungsIntervall: FachleistungsIntervall.woechentlich,
        verbrauchteStunden: 85.0,
        kostenuebernahme: 'Bezirksamt Charlottenburg-Wilmersdorf',
        kostenuebernahmeVon: DateTime(2024, 11, 1),
        kostenuebernahmeBis: DateTime(2026, 10, 31),
        notes: 'Bipolare Störung, Unterstützung Finanzen und Behördengänge',
        assignedEmployees: ['demo-ma-1', 'demo-ma-3'],
        responsibleEmployeeId: 'demo-ma-1',
        deputyEmployeeId: 'demo-ma-3',
        customFields: {},
        createdAt: now,
        updatedAt: now,
      ),
      Client(
        id: 'demo-kl-4',
        firstName: 'Markus',
        lastName: 'Hoffmann',
        dateOfBirth: DateTime(2002, 1, 28),
        status: ClientStatus.active,
        priority: ClientPriority.high,
        services: [ServiceType.ambulant, ServiceType.arbeit],
        betreuungSeit: DateTime(2026, 1, 10),
        hilfeTyp: HilfeTyp.eingliederungshilfe,
        fachleistungsstunden: 10,
        fachleistungsIntervall: FachleistungsIntervall.woechentlich,
        verbrauchteStunden: 18.0,
        kostenuebernahme: 'Bezirksamt Friedrichshain-Kreuzberg',
        kostenuebernahmeVon: DateTime(2026, 1, 10),
        kostenuebernahmeBis: DateTime(2027, 1, 9),
        notes: 'PTBS und Angststörung, Aufbau Tagesstruktur und Berufsvorbereitung',
        assignedEmployees: ['demo-ma-2'],
        responsibleEmployeeId: 'demo-ma-2',
        customFields: {},
        createdAt: now,
        updatedAt: now,
      ),
      Client(
        id: 'demo-kl-5',
        firstName: 'Natalia',
        lastName: 'Petrov',
        dateOfBirth: DateTime(1978, 9, 12),
        status: ClientStatus.active,
        priority: ClientPriority.medium,
        services: [ServiceType.ambulant, ServiceType.begleitung],
        betreuungSeit: DateTime(2025, 3, 1),
        hilfeTyp: HilfeTyp.eingliederungshilfe,
        fachleistungsstunden: 7,
        fachleistungsIntervall: FachleistungsIntervall.woechentlich,
        verbrauchteStunden: 56.5,
        kostenuebernahme: 'Bezirksamt Pankow',
        kostenuebernahmeVon: DateTime(2025, 3, 1),
        kostenuebernahmeBis: DateTime(2026, 2, 28),
        notes: 'Emotional instabile Persönlichkeitsstörung, Krisenintervention und Alltagsbewältigung',
        assignedEmployees: ['demo-ma-3'],
        responsibleEmployeeId: 'demo-ma-3',
        customFields: {},
        createdAt: now,
        updatedAt: now,
      ),
      Client(
        id: 'demo-kl-6',
        firstName: 'Jens',
        lastName: 'Braun',
        dateOfBirth: DateTime(1958, 4, 19),
        status: ClientStatus.active,
        priority: ClientPriority.medium,
        services: [ServiceType.ambulant, ServiceType.wohnen],
        betreuungSeit: DateTime(2025, 1, 15),
        hilfeTyp: HilfeTyp.eingliederungshilfe,
        fachleistungsstunden: 6,
        fachleistungsIntervall: FachleistungsIntervall.woechentlich,
        verbrauchteStunden: 62.0,
        kostenuebernahme: 'Bezirksamt Spandau',
        kostenuebernahmeVon: DateTime(2025, 1, 15),
        kostenuebernahmeBis: DateTime(2026, 1, 14),
        notes: 'Chronische Depression und Suchterkrankung, Wohnraumsicherung und Gesundheitsförderung',
        assignedEmployees: ['demo-ma-1'],
        responsibleEmployeeId: 'demo-ma-1',
        customFields: {},
        createdAt: now,
        updatedAt: now,
      ),
    ];

    for (final client in demoClients) {
      try {
        await ref.read(clientProvider.notifier).addClient(client);
      } catch (_) {}
    }
  }
}
